### ISSUE TITLE
Implement best_next_move API

### ISSUE THREAD

**Issue by truongluan303** [Bao-projects/tictactoe-core#10]
Now, assume that `best_next_move` function in `tictactoe_core.py` has been implemented (You don't need to touch anything in `tictactoe_core.py`, just assume the function is working even though it's just always returning [0,0] for now), create a GET API for it like how we created the `board_status` API.
This means when you run the backend service with `python3 app.py` and send a GET request to `http://127.0.0.1:5000/best_next_move`, you should get a valid response.

Design your solution here first, once your design is approved by me then you can start coding it out. Your design should mention these things:
- What is the API input (form data input), give an example form data input.
- What is the API output if the input is valid and what is the API output if the input is not valid (Refer to this ticket https://github.com/Bao-projects/tictactoe-core/issues/4, your design should look quite similar).

Once you're done with the design, the files that you should touch on are `src/routes/best_next_move.py` and `src/routes/helper/response.py`, I've marked the TODO items in there. All the remaining files should NOT be touched.

**Comment by truongluan303** [comment]
@BaoThan put a comment here for the design once you're done

**Comment by BaoThan** [comment]
What is the API input (form data input), give an example form data input.

- is_valid: bool
- board (an array) 
- current player turn X or O

What is the API output if the input is valid and what is the API output if the input is not valid?

- API output if the input is valid:

return(
       jsonify(
                     {
                           "success": True,
                            "data": {
                                                "is_valid": self.is_valid,
                                                "board": self.board,
                                                "current_player": self.current_player,
                                          },
                      })
                 )
- API output if the input is not valid
{
    "success": false,
    "error_message": "Invalid board."
}

**Comment by BaoThan** [comment]
@truongluan303  I think I get the answer wrong I just redundanted thing. this may be the better answer:
the output if the input is valid:
(
"success": True
"move": [0,0] #coordinate for the best move. 
)200,

**Comment by truongluan303** [comment]
Why do we need is_valid for input?

**Comment by truongluan303** [comment]
@BaoThan other than the input the rest looks good, you can start coding on that
